language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

# NOTE(dustin): Preemptively install a specific version of coverage. We're having issues with the 5.x ones.
  - pip install coverage==4.5.4

  - pip install coveralls
  - pip install nose
script: nosetests -s -v --with-coverage --cover-package=inotify
after_success:
  - coveralls
